# Values for dbeaver.
# helm push dbeaver-0.0.1.tgz oci://registry-1.docker.io/janben
# helm upgrade --install dbeaver ./dbeaver -f values.yaml

replicaCount: 1
hostNetwork: false
image:
  repository: dbeaver/cloudbeaver
  pullPolicy: IfNotPresent
  tag: "25.0.4"

securityContext: {}

certManager:
  enabled: false
  clusterIssuer:
    issuerRef: letsencrypt

service:
  type: ClusterIP
  name: http
  port: 80
  protocol: TCP
  targetPort: 8978

ingress:
  enabled: true
  customResourceEnabled: false # use custom resource provided Ingress (not recommended because it uses old API version of Ingress)
  tlsEnabled: true
  tlsSecretName: "dbeaver.{{ .Values.domain }}"
  hostname: "dbeaver.{{ .Values.domain }}"
  annotations:
    #kubernetes.io/ingress.class: nginx
    spec.ingressClassName: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  path: "/"

storage:
  # storageClassName: ""
  capacity: 5Gi

resources:
  requests:
    cpu: 100m
    memory: "128Mi"
  limits:
    cpu: 500m
    memory: "512Mi"

domain: mydomain.com